import Head from 'next/head';
import Image from 'next/image';
import { Main } from '../components/main';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        {/* fonts */}
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@300;400;700&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="assets/vendors/bootstrap/css/bootstrap.min.css"
        />
        <link rel="stylesheet" href="assets/vendors/animate/animate.min.css" />
        <link
          rel="stylesheet"
          href="assets/vendors/fontawesome/css/all.min.css"
        />
        <link rel="stylesheet" href="assets/vendors/jarallax/jarallax.css" />
        <link
          rel="stylesheet"
          href="assets/vendors/jquery-magnific-popup/jquery.magnific-popup.css"
        />
        <link
          rel="stylesheet"
          href="assets/vendors/nouislider/nouislider.min.css"
        />
        <link
          rel="stylesheet"
          href="assets/vendors/nouislider/nouislider.pips.css"
        />
        <link
          rel="stylesheet"
          href="assets/vendors/odometer/odometer.min.css"
        />
        <link rel="stylesheet" href="assets/vendors/swiper/swiper.min.css" />
        <link rel="stylesheet" href="assets/vendors/moniz-icons/style.css" />
        <link
          rel="stylesheet"
          href="assets/vendors/tiny-slider/tiny-slider.min.css"
        />
        <link rel="stylesheet" href="assets/vendors/reey-font/stylesheet.css" />
        <link
          rel="stylesheet"
          href="assets/vendors/owl-carousel/owl.carousel.min.css"
        />
        <link
          rel="stylesheet"
          href="assets/vendors/owl-carousel/owl.theme.default.min.css"
        />
        <link
          rel="stylesheet"
          href="assets/vendors/twentytwenty/twentytwenty.css"
        />
        <link
          rel="stylesheet"
          href="assets/vendors/bxslider/jquery.bxslider.css"
        />
        <link
          rel="stylesheet"
          href="assets/vendors/bootstrap-select/css/bootstrap-select.min.css"
        />
        <link rel="stylesheet" href="assets/vendors/vegas/vegas.min.css" />
        <link rel="stylesheet" href="assets/vendors/jquery-ui/jquery-ui.css" />
        <link
          rel="stylesheet"
          href="assets/vendors/timepicker/timePicker.css"
        />
        {/* template styles */}
        <link rel="stylesheet" href="assets/css/moniz.css" />
        <link rel="stylesheet" href="assets/css/moniz-responsive.css" />
        {/* RTL Styles */}
        <link rel="stylesheet" href="assets/css/moniz-rtl.css" />
        {/* color css */}
        <link
          rel="stylesheet"
          id="jssDefault"
          href="assets/css/colors/color-default.css"
        />
        <link
          rel="stylesheet"
          id="jssMode"
          href="assets/css/modes/moniz-normal.css"
        />
        {/* toolbar css */}
        <link rel="stylesheet" href="assets/css/moniz-toolbar.css" />
      </Head>

      <Main />

      <a href="#" data-target="html" className="scroll-to-target scroll-to-top">
        <i className="fa fa-angle-up"></i>
      </a>

      <script src="assets/vendors/jquery/jquery-3.5.1.min.js"></script>
      <script src="assets/vendors/bootstrap/js/bootstrap.bundle.min.js"></script>
      <script src="assets/vendors/jarallax/jarallax.min.js"></script>
      <script src="assets/vendors/jquery-ajaxchimp/jquery.ajaxchimp.min.js"></script>
      <script src="assets/vendors/jquery-appear/jquery.appear.min.js"></script>
      <script src="assets/vendors/jquery-circle-progress/jquery.circle-progress.min.js"></script>
      <script src="assets/vendors/jquery-magnific-popup/jquery.magnific-popup.min.js"></script>
      <script src="assets/vendors/jquery-validate/jquery.validate.min.js"></script>
      <script src="assets/vendors/nouislider/nouislider.min.js"></script>
      <script src="assets/vendors/odometer/odometer.min.js"></script>
      <script src="assets/vendors/swiper/swiper.min.js"></script>
      <script src="assets/vendors/tiny-slider/tiny-slider.min.js"></script>
      <script src="assets/vendors/wnumb/wNumb.min.js"></script>
      <script src="assets/vendors/wow/wow.js"></script>
      <script src="assets/vendors/isotope/isotope.js"></script>
      <script src="assets/vendors/countdown/countdown.min.js"></script>
      <script src="assets/vendors/owl-carousel/owl.carousel.min.js"></script>
      <script src="assets/vendors/twentytwenty/twentytwenty.js"></script>
      <script src="assets/vendors/twentytwenty/jquery.event.move.js"></script>
      <script src="assets/vendors/bxslider/jquery.bxslider.min.js"></script>
      <script src="assets/vendors/bootstrap-select/js/bootstrap-select.min.js"></script>
      <script src="assets/vendors/vegas/vegas.min.js"></script>
      <script src="assets/vendors/jquery-ui/jquery-ui.js"></script>
      <script src="assets/vendors/timepicker/timePicker.js"></script>

      <script src="http://maps.google.com/maps/api/js?key=AIzaSyATY4Rxc8jNvDpsK8ZetC7JyN4PFVYGCGM"></script>

      <script src="assets/js/moniz.js"></script>
    </div>
  );
}
